Box:
  Typography:
    strong: '{editProducts ? ''Edit Product'' : ''Add Product''}'
  Box:
    TextField:
      '#text': |-
        setName(e.target.value)}
                  fullWidth
                />
      TextField:
        '#text': |-
          setQuantity(e.target.value)}
                    fullWidth
                  />
        TextField:
          '#text': |-
            setPrice(e.target.value)}
                      fullWidth
                    />
          Box:
            '#text': '{editProducts && ()}'
            Button:
              - '{editProducts ? ''Update'' : ''Add''} Product'
              - |-
                navigate("/products")}
                            >
                              Cancel
